import Link from "next/link";
import Head from "next/head";
// import { client } from "../utils/client";
import { useState } from "react";
import { motion } from "framer-motion";

import styles from "../styles/Home.module.css";

export default function Home({ projects }) {
  const [Home, setHome] = useState(false);
  const [Projects, setProjects] = useState(false);
  const [Skills, setSkills] = useState(false);
  const [Contact, setContact] = useState(false);

  const turnOffAnimation = (setstate) => {
    const timeOutOffAnimation = setTimeout(() => {
      setstate(false);
    }, 600);
  };

  return (
    <motion.div
      animate={{ y: "0%" }}
      exit={{ opacity: 1 }}
      initial={{ y: "100%" }}
      transition={{
        duration: 0.75,
        ease: "easeOut",
      }}
      className={styles.test}
    >
      <Head>
        <title>PortFolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.main_top}>
          <h1 className={styles.main_top_h1}>
            Hello, I'm Matthieu, a front-end developer with a passion for
            creating beautiful and functional websites.
          </h1>
        </div>

        <div className={styles.main_middle}>
          <h2>
            I am specialized with modern technologies built around the
            JavaScript framework, such as React, Next.js and TypeScript. I have
            a passion for CSS and strive to create visually appealing designs.
            Additionally, I have experience working with back-end technologies
            like Node.js
          </h2>
        </div>
        <div className={styles.main_middle}>
          <h2>
            I am specialized with modern technologies built around the
            JavaScript framework, such as React, Next.js and TypeScript. I have
            a passion for CSS and strive to create visually appealing designs.
            Additionally, I have experience working with back-end technologies
            like Node.js
          </h2>
        </div>
        <div className={styles.main_middle}>
          <h2>
            I am specialized with modern technologies built around the
            JavaScript framework, such as React, Next.js and TypeScript. I have
            a passion for CSS and strive to create visually appealing designs.
            Additionally, I have experience working with back-end technologies
            like Node.js
          </h2>
        </div>
        <div className={styles.main_middle}>
          <h2>
            I am specialized with modern technologies built around the
            JavaScript framework, such as React, Next.js and TypeScript. I have
            a passion for CSS and strive to create visually appealing designs.
            Additionally, I have experience working with back-end technologies
            like Node.js
          </h2>
        </div>
        <div className={styles.main_middle}>
          <h2>
            I am specialized with modern technologies built around the
            JavaScript framework, such as React, Next.js and TypeScript. I have
            a passion for CSS and strive to create visually appealing designs.
            Additionally, I have experience working with back-end technologies
            like Node.js
          </h2>
        </div>
        <div className={styles.main_middle}>
          <h2>
            I am specialized with modern technologies built around the
            JavaScript framework, such as React, Next.js and TypeScript. I have
            a passion for CSS and strive to create visually appealing designs.
            Additionally, I have experience working with back-end technologies
            like Node.js
          </h2>
        </div>
        <div className={styles.main_middle}>
          <h2>
            I am specialized with modern technologies built around the
            JavaScript framework, such as React, Next.js and TypeScript. I have
            a passion for CSS and strive to create visually appealing designs.
            Additionally, I have experience working with back-end technologies
            like Node.js
          </h2>
        </div>
        <div className={styles.main_middle}>
          <h2>
            I am specialized with modern technologies built around the
            JavaScript framework, such as React, Next.js and TypeScript. I have
            a passion for CSS and strive to create visually appealing designs.
            Additionally, I have experience working with back-end technologies
            like Node.js
          </h2>
        </div>
        <div className={styles.main_bottom}>
          <div className={styles.main_bottom_date}>
            ©2023 <span>Open to work</span>
          </div>
        </div>
      </main>
    </motion.div>
  );
}

// export async function getStaticProps() {
//   const projects = await client.fetch(`*[_type == "projects"]`);

//   return {
//     props: {
//       projects,
//     },
//   };
// }
